#!/bin/bash
EXPORT_DIR="../CodeHeistExport"
EXPORT_NAME="CodeHeist"
PROJECT_DIR=$PWD

# Main exports
echo "Exporting builds to $EXPORT_DIR"
mkdir -p "$EXPORT_DIR"

echo "  Exporting windows builds to $EXPORT_DIR/windows/"
mkdir -p "$EXPORT_DIR/windows"
godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"

echo "  Exporting linux build to $EXPORT_DIR/linux/"
mkdir -p "$EXPORT_DIR/linux"
godot --headless --verbose --export-release "Linux" "$EXPORT_DIR/linux/$EXPORT_NAME.x86_64"

echo "  Exporting web build to $EXPORT_DIR/web/"
mkdir -p "$EXPORT_DIR/web"
godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"

# Pages local repo
if [[ $* == *-p* ]]
then
    echo "  Exporting web build to $EXPORT_DIR/pages/game"
    mkdir -p "$EXPORT_DIR/pages/game"
    godot --headless --verbose --export-release "Web" "$EXPORT_DIR/pages/game/index.html"
fi
if [[ $* == *-g* ]]
then
    cd "$EXPORT_DIR/pages"
    git add *
    git status
    git commit -m "Autogenerated updated from local system."
    if [[ $* == *-gu* ]]
    then
        git push
    fi
    cd $PROJECT_DIR
fi
